name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Compilation du projet
        run: make

      - name: Nettoyage
        run: make clean
      